export type TsgoDiagnosticSeverity = 'error' | 'message' | 'suggestion' | 'warning'

export const expectedPackageBaseline = {
  'effect': '4.0.0-beta.92',
  '@effect/platform-node': '4.0.0-beta.92',
  '@effect/vitest': '4.0.0-beta.92',
  '@effect/tsgo': '0.15.0',
  '@effect/language-service': '0.86.2',
  '@typescript/native-preview': '7.0.0-dev.20260630.1',
  '@antfu/eslint-config': '^9.0.0',
  'eslint': '^10.3.0',
  'vitest': '^4.1.8',
} as const

export const expectedEffectTsgoVersion = '0.15.0'
export const expectedPrepareCommand = 'effect-tsgo patch'
export const expectedTypecheckCommand = 'tsgo --noEmit'

export const strictDiagnosticSeverity = {
  anyUnknownInErrorContext: 'error',
  asyncFunction: 'warning',
  catchAllToMapError: 'suggestion',
  catchToOrElseSucceed: 'suggestion',
  catchUnfailableEffect: 'suggestion',
  classSelfMismatch: 'error',
  cryptoRandomUUID: 'warning',
  cryptoRandomUUIDInEffect: 'warning',
  deterministicKeys: 'warning',
  duplicatePackage: 'warning',
  effectDoNotation: 'warning',
  effectFnIife: 'warning',
  effectFnImplicitAny: 'error',
  effectFnOpportunity: 'suggestion',
  effectGenUsesAdapter: 'warning',
  effectInFailure: 'warning',
  effectInVoidSuccess: 'warning',
  effectMapFlatten: 'suggestion',
  effectMapVoid: 'suggestion',
  effectSucceedWithVoid: 'suggestion',
  extendsNativeError: 'warning',
  floatingEffect: 'error',
  genericEffectServices: 'warning',
  globalConsole: 'warning',
  globalConsoleInEffect: 'warning',
  globalDate: 'warning',
  globalDateInEffect: 'warning',
  globalErrorInEffectCatch: 'warning',
  globalErrorInEffectFailure: 'warning',
  globalFetch: 'warning',
  globalFetchInEffect: 'warning',
  globalRandom: 'warning',
  globalRandomInEffect: 'warning',
  globalTimers: 'warning',
  globalTimersInEffect: 'warning',
  instanceOfSchema: 'warning',
  layerMergeAllWithDependencies: 'warning',
  lazyEffect: 'suggestion',
  lazyPromiseInEffectSync: 'warning',
  leakingRequirements: 'suggestion',
  missedPipeableOpportunity: 'warning',
  missingEffectContext: 'error',
  missingEffectError: 'error',
  missingLayerContext: 'error',
  missingReturnYieldStar: 'error',
  missingStarInYieldEffectGen: 'error',
  multipleCatchTag: 'suggestion',
  multipleEffectProvide: 'warning',
  nestedEffectGenYield: 'warning',
  newPromise: 'warning',
  newSchemaClass: 'warning',
  nodeBuiltinImport: 'warning',
  outdatedApi: 'warning',
  overriddenSchemaConstructor: 'error',
  preferSchemaOverJson: 'warning',
  processEnv: 'warning',
  processEnvInEffect: 'warning',
  redundantMapError: 'suggestion',
  redundantOrDie: 'suggestion',
  redundantSchemaTagIdentifier: 'suggestion',
  returnEffectInGen: 'suggestion',
  runEffectInsideEffect: 'suggestion',
  schemaNumber: 'suggestion',
  schemaStructWithTag: 'suggestion',
  serviceNotAsClass: 'warning',
  strictBooleanExpressions: 'warning',
  strictEffectProvide: 'warning',
  tryCatchInEffectGen: 'suggestion',
  unknownInEffectCatch: 'warning',
  unnecessaryArrowBlock: 'warning',
  unnecessaryEffectGen: 'suggestion',
  unnecessaryFailYieldableError: 'suggestion',
  unnecessaryPipe: 'suggestion',
  unnecessaryPipeChain: 'suggestion',
  unnecessaryTypeofType: 'suggestion',
  unsafeEffectTypeAssertion: 'warning',
} as const satisfies Readonly<Record<string, TsgoDiagnosticSeverity>>

export const strictDiagnosticGate = {
  includeSuggestionsInTsc: true,
  ignoreEffectSuggestionsInTscExitCode: false,
  ignoreEffectWarningsInTscExitCode: false,
  ignoreEffectErrorsInTscExitCode: false,
} as const

export const strictLanguageServicePlugin = {
  name: '@effect/language-service',
  diagnostics: true,
  ...strictDiagnosticGate,
  diagnosticSeverity: strictDiagnosticSeverity,
  barrelImportPackages: ['effect'],
  topLevelNamedReexports: 'follow',
  effectFn: ['span'],
  keyPatterns: [
    {
      target: 'service',
      pattern: 'default',
      skipLeadingPath: ['src/'],
    },
    {
      target: 'error',
      pattern: 'default',
      skipLeadingPath: ['src/'],
    },
    {
      target: 'custom',
      pattern: 'default',
      skipLeadingPath: ['src/'],
    },
  ],
  extendedKeyDetection: true,
  layerGraphFollowDepth: 1,
  noExternal: true,
  inlays: true,
  allowedDuplicatedPackages: [],
  pipeableMinArgCount: 2,
} as const

export const requiredTsgoPolicyKeywords = [
  'POLICY_NATIVE_BACKEND',
  'POLICY_DIAGNOSTIC_GATE',
  'POLICY_RULE_MAP',
  'POLICY_IMPORT_STYLE',
  'POLICY_OVERRIDES',
  'POLICY_SUPPRESSIONS',
  'POLICY_KEY_PATTERNS',
  'POLICY_LAYER_GRAPH',
  'POLICY_UPGRADE_LOOP',
  'VERIFIER_CONTRACT',
] as const
